version: '3'

services:
    #pools:
    #    image: pd/pools:${TAG:-latest}

    #pools-data-fetcher:
    #    image: pd/pools-data-fetcher:${TAG:-latest}
    #    build:
    #        context: ./services/pool_datastream_fetcher
    #        dockerfile: Dockerfile
        
    #    depends_on:
    #        - kafka
    #        - pools

    opportunities-primary-search:
        image: pd/opportunities-primary-search:${TAG:-latest}
        build:
            context: ./rust/opportunities_primary_search
            dockerfile: Dockerfile
        depends_on:
            - kafka
    
    #pools-data-processor:
    #    image: pd/pools-data-processor:${TAG:-latest}
    #    depends_on:
    #        - kafka

    #opportunities-prepare:
    #    image: pd/opportunities-prepare:${TAG:-latest}
    #    depends_on:
    #        - kafka

    #arbitrage-execute:
    #    image: pd/arbitrage-execute:${TAG:-latest}
    #    depends_on:
    #        - kafka
    #        - pools
